### ISSUE TITLE
Bug?: GQtyError: Internal server error

### ISSUE THREAD

**Issue by m1kit** [wpengine/faustjs#666]
## Applicable Versions

- `@faustjs/core` version: 0.12.3
- `@faustjs/react` version: 0.12.0
- `@faustjs/next` version: 0.12.3
- WordPress version: 5.8.2

## Steps To Reproduce

1. Set up the faust.js following [this doc](https://faustjs.org/docs/next/getting-started)
2. Open the preview from editing screen

## The current behavior
Browser screenshot
<img width="1621" alt="スクリーンショット 2021-11-29 23 23 52" src="https://user-images.githubusercontent.com/37488201/143884970-9089fc22-488c-4955-88d1-81369307ce58.png">

Next.js console output
```
[GQtyError: Internal server error] {
  graphQLErrors: [
    {
      message: 'Internal server error',
      extensions: [Object],
      locations: [Array],
      path: [Array]
    }
  ]
}
```

## The expected behavior
We can see the contents like
<img width="1617" alt="スクリーンショット 2021-11-29 23 25 10" src="https://user-images.githubusercontent.com/37488201/143885167-62f9b210-503e-4ece-9b66-4e7e4dd640fa.png">

No errors in the console

**Comment by m1kit** [comment]
> @m1kit Try upgrading to `0.13.1` all @faustjs packages (`@faustjs/core`, `@faustjs/react`, `@faustjs/next`).

I replaced the frontend with [the latest example](https://github.com/wpengine/faustjs/tree/canary/examples/next/getting-started), but the issue remains.

Here's our `docker-compose.yml` (we put the example project under `frontend` folder and edit `Hosts` to route `blog.example.com` to `localhost`.)

```
version: '3'

services:

  frontend:
    command: "./run.sh"
    build: ./frontend
    volumes:
      - "./frontend/:/var/www/frontend"
    working_dir: /var/www/frontend
    environment:
      NODE_ENV: development
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=3000
      - traefik.http.routers.frontend.rule=Host(`blog.example.com`)
      - traefik.http.routers.frontend.entrypoints=web

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - web

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.services.wordpress.loadbalancer.server.port=80
      - traefik.http.routers.wordpress.rule=Host(`blog.example.com`)&&
        PathPrefix(`/graphql`, `/wp-`)
      - traefik.http.routers.wordpress.entrypoints=web

  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    command:
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=web"
      - "--entryPoints.web.address=:80"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      web:
        aliases:
          - blog.example.com

volumes:
  db_data: null
  wp_data: null
networks:
  web: null
```

**Comment by blakewilson** [comment]
@m1kit Two things I would try:

* Turn on query logging. This might help point you in the right direction. https://faustjs.org/docs/next/guides/logging-queries
* I would also try and run your frontend outside of Docker to see if this issue is related to Docker Compose

**Comment by m1kit** [comment]
I resolved the issue by adding this in `docker-compose.yml`.

```yml
services:
  wordpress:
    labels:
      - traefik.http.routers.wordpress.rule=Host(`blog.example.com`)&&
        PathPrefix(`/graphql`, `/wp-`, `/generate`)
```

We need to forward `/generate` to the wordpress backend for the preview feature.
